steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/vivid-partition-313706/c0-deeplearning-common-cu110-v20210512-debian-10', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/vivid-partition-313706/c0-deeplearning-common-cu110-v20210512-debian-10']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'taskclose', '--image', 'gcr.io/vivid-partition-313706/c0-deeplearning-common-cu110-v20210512-debian-10', '--region', 'us-central1', '--platform', 'managed']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'services', 'add-iam-policy-binding', '--project=taskclose','--platform=managed', '--region=asia-northeast1', 'taskclose', '--member=allUsers', '--role=roles/run.invoker']
images:
  - gcr.io/vivid-partition-313706/c0-deeplearning-common-cu110-v20210512-debian-10