steps:
- name: 'bash'
  args: ["mv", "-f", "services/config/app.yaml", "services/taskclose"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/vivid-partition-313706/footer-nginx:master', '--file=services/footer-nginx/Dockerfile', "."]